/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Space Grotesk', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      colors: {
        primary: '#E31B23',
        outline: '#000000',
        'on-background': '#000000',
        'primary-fixed': '#E31B23',
        'primary-fixed-dim': '#C00015',
        'on-primary': '#FFFFFF',
        'surface-container-highest': '#E5E5E5',
        'surface-container-high': '#F5F5F5',
        'surface-container': '#FBFBFB',
        'surface-container-low': '#FAFAFA',
        'surface-container-lowest': '#FFFFFF',
        'surface-bright': '#FFFFFF',
        'surface': '#FFFFFF',
        'surface-variant': '#F0F0F0',
        'surface-dim': '#F0F0F0',
        'on-surface': '#000000',
        'on-surface-variant': '#333333',
        'inverse-surface': '#000000',
        'inverse-on-surface': '#FFFFFF',
        'inverse-primary': '#FFFFFF',
        'outline-variant': '#CCCCCC',
        'tertiary': '#333333',
        'tertiary-fixed': '#000000',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#333333',
        'on-tertiary-container': '#000000',
        'secondary': '#000000',
        'on-secondary': '#FFFFFF',
        'secondary-fixed': '#000000',
        'secondary-fixed-dim': '#CCCCCC',
        'on-secondary-fixed': '#000000',
        'on-secondary-fixed-variant': '#333333',
        'secondary-container': '#F0F0F0',
        'on-secondary-container': '#333333',
        'error': '#E31B23',
        'on-error': '#FFFFFF',
        'error-container': '#C00015',
        'on-error-container': '#FFFFFF',
        'surface-tint': '#E31B23',
        'primary-container': '#E31B23',
        'on-primary-container': '#FFFFFF',
        'on-tertiary-fixed-variant': '#333333',
        'tertiary-fixed-dim': '#666666',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
    },
  },
  plugins: [],
}
