import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';
import type { Language } from '../types';

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TransKey) => string;
}

export type TransKey = keyof typeof translations.vi;

const translations = {
  vi: {
    navbar_home: 'Trang_Chủ',
    navbar_about: 'Giới_Thiệu',
    navbar_experience: 'Kinh_Nghiệm',
    navbar_skills: 'Kỹ_Năng',
    navbar_projects: 'Dự_Án',
    navbar_contact: 'Liên_Hệ',
    hero_status: 'TRẠNG_THÁI: TRỰC_TUYẾN',
    hero_greeting: 'XIN CHÀO, TÔI LÀ',
    hero_name: 'Bùi Hoàng Việt',
    hero_subtitle: 'Lập trình viên Frontend đầy đam mê, chuyên xây dựng giao diện web hiện đại và trải nghiệm người dùng mượt mà. Luôn học hỏi công nghệ mới để tạo ra những sản phẩm chất lượng.',
    hero_btnProject: 'THUÊ TÔI',
    hero_btnArsenal: 'TẢI CV',
    hero_expBadge: '8+',
    hero_expLabel: 'Năm_Kinh_Nghiệm',
    hero_stat_years: 'Năm_Kinh_Nghiệm',
    hero_stat_projects: 'Dự_Án_Hoàn_Thành',
    hero_stat_tech: 'Công_Nghệ_Sử_Dụng',
    hero_edu: 'HUST — CS 2025',
    hero_student: 'Đang tìm việc',
    narrative_title: 'Tiểu_Sử',
    about_title: 'Tiểu_Sử',
    about_fullname: 'Họ_tên',
    about_fullname_val: 'Bùi Hoàng Việt',
    about_birth: 'Năm_sinh',
    about_birth_val: '15/10/2003',
    about_university: 'Trường',
    about_univ_val: 'ĐH KT-KTCN Hà Nội',
    about_gpa: 'GPA',
    about_gpa_val: '3.1 / 4.0',
    about_major: 'Ngành',
    about_major_val: 'Công nghệ Thông tin',
    about_email: 'Email',
    about_email_val: 'bhviet1510@gmail.com',
    about_phone: 'SĐT',
    about_phone_val: '+84 912 687 955',
    about_location: 'Địa_chỉ',
    about_location_val: 'Hà Nội, Việt Nam',
    about_bio1: 'Tôi là một lập trình viên Frontend đầy đam mê, luôn tìm kiếm những giải pháp sáng tạo cho giao diện người dùng. Thành thạo Vue 3 và React để xây dựng những trải nghiệm web hiện đại, mượt mà.',
    about_bio2: 'Mục tiêu của tôi là không ngừng học hỏi, phát triển kỹ năng chuyên môn để trở thành một Full-Stack Developer toàn diện, đóng góp giá trị thực sự cho cộng đồng công nghệ.',
    about_edu_title: 'Học_Vấn',
    about_school: 'Đại học Kinh tế — Kỹ thuật Công nghiệp Hà Nội',
    about_major_school: 'Công nghệ Thông tin',
    about_goals_title: 'Mục_Tiêu_3_Năm',
    about_goal1: 'Trở thành Full-stack Developer chuyên nghiệp',
    about_goal2: 'Nắm vững các công nghệ Cloud (AWS / Azure)',
    about_goal3: 'Đóng góp cho các dự án Open Source lớn',
    about_goal4: 'Xây dựng sản phẩm công nghệ có ích cho cộng đồng',
    narrative_edu_section_title: 'Hồ_Sơ_Học_Vấn',
    narrative_edu_label: 'HỆ_THỐNG_KHỞI_TẠO',
    narrative_edu_school: 'Đại học Bách Khoa Hà Nội',
    narrative_edu_period: '2014 — 2019',
    narrative_edu_degree: 'Cử nhân Khoa học Máy tính',
    narrative_edu_gpa_label: 'Điểm trung bình (GPA)',
    narrative_edu_gpa: '3.8 / 4.0',
    narrative_career_section_title: 'Tóm_Tắt_Nghề_Nghiệp',
    narrative_career_label: 'HÀNH_TRÌNH_CÔNG_NGHỆ',
    narrative_current_period: '2021 — HIỆN TẠI',
    narrative_current_title: 'Kiến trúc sư hệ thống chính',
    narrative_current_summary: 'Thiết kế các kiến trúc microservices có khả năng chịu lỗi cao và dẫn dắt các sáng kiến mở rộng cơ sở hạ tầng cốt lõi cho các nền tảng Fintech.',
    narrative_past_period: '2019 — 2021',
    narrative_past_title: 'Kỹ sư Full-Stack',
    narrative_past_summary: 'Phát triển các bảng điều khiển doanh nghiệp phức tạp và các API hiệu suất cao sử dụng T3 stack và tính toán tại biên (edge computing).',
    narrative_career_summary: '8 năm kiến tạo hệ thống từ kiến trúc vi mô đến nguyên khối. Từ thực tập sinh tại VNG đến Lead System Architect tại Monolith Systems JSC.',
    exp_title: 'Kinh_Nghiệm_Chuyên_Môn',
    exp_current: 'Hiện Tại',
    exp_role1_company: 'TD Clinic',
    exp_role1_title: 'Freelance Frontend Developer',
    exp_role1_period: '02/2026 — 04/2026',
    exp_role1_task1: 'Xây dựng hệ thống frontend hoàn chỉnh với React, TypeScript theo kiến trúc module-based.',
    exp_role1_task2: 'Triển khai phân quyền và protected routes với React Router.',
    exp_role1_task3: 'Xây dựng chức năng xác thực (authentication) và quản lý session khi làm việc với API.',
    exp_role1_task4: 'Phát triển hệ thống đặt lịch khám theo time slot, hỗ trợ nhiều bác sĩ và giảm xung đột lịch.',
    exp_role1_task5: 'Quản lý state toàn cục bằng Redux Toolkit, đảm bảo dữ liệu nhất quán.',
    exp_role1_task6: 'Xây dựng component tái sử dụng (Table, Modal, Pagination...).',
    exp_role1_task7: 'Tích hợp RESTful API với Axios, xử lý loading và error.',
    exp_role1_task8: 'Xây dựng UI với Tailwind CSS và Ant Design.',
    exp_role1_task9: 'Hiển thị dữ liệu bằng biểu đồ với Recharts.',
    exp_role1_task10: 'Hỗ trợ đa ngôn ngữ với i18next.',
    exp_role1_task11: 'Tối ưu hiệu năng với lazy loading, code splitting.',
    exp_role1_task12: 'Triển khai ứng dụng với Docker và Nginx.',
    exp_role2_company: 'SmartOSC',
    exp_role2_title: 'Intern Front-end',
    exp_role2_period: '09/2025 — 11/2025',
    exp_role2_task1: 'Tham gia dự án phát triển giao diện SPA bằng Vue 3 + TypeScript.',
    exp_role2_task2: 'Sử dụng Pinia để quản lý state tập trung, tối ưu hiệu suất và khả năng tái sử dụng dữ liệu.',
    exp_role2_task3: 'Triển khai Composition API, tách logic xử lý ra các file composable và utils.',
    exp_role2_task4: 'Gọi và xử lý RESTful API qua Axios, đồng bộ hóa dữ liệu với backend.',
    exp_role2_task5: 'Viết component tái sử dụng, áp dụng best practice về props, emits, lifecycle hooks.',
    exp_role2_task6: 'Học và thực hành quy trình làm việc nhóm chuyên nghiệp với Git (branching, merge, pull request).',
    exp_role2_task7: 'Implement responsive UI từ Figma designs, đảm bảo tương thích đa thiết bị.',
    exp_role2_task8: 'Được đào tạo và làm việc thực tế với Laravel Backend.',
    exp_role3_company: 'Mattech',
    exp_role3_title: 'Intern Front-end',
    exp_role3_period: '11/2024 — 05/2025',
    exp_role3_task1: 'Phát triển và chỉnh sửa giao diện website bằng React TypeScript, sử dụng component tái sử dụng.',
    exp_role3_task2: 'Thiết kế giao diện responsive trên nhiều thiết bị với Tailwind CSS.',
    exp_role3_task3: 'Quản lý mã nguồn với Git & GitLab, thực hiện merge/pull request, review code nhóm.',
    exp_role3_task4: 'Được đào tạo về Backend (Laravel PHP), làm việc với API thực tế.',
    exp_role3_task5: 'Áp dụng các React Hooks (useState, useEffect, useMemo, useContext) trong xử lý logic và tối ưu hiệu năng.',
    exp_role3_task6: 'Tích hợp RESTful API với Axios, xử lý loading và error state.',
    skill_title: 'Kỹ_Năng',
    skill_fe: '01. FRONTEND',
    skill_be: '02. BACKEND',
    skill_ui: '03. UI_LIBRARIES',
    skill_tools: '04. TOOLS',
    proj_title: 'Dự_Án_Triển_Khai',
    proj_deployed: 'ĐÃ_TRIỂN_KHAI',
    proj_beta: 'BẢN_THỬ_NGHIỆM',
    proj_crypto_chart_name: 'Crypto Real-time Chart Dashboard',
    proj_crypto_chart_desc: 'Ứng dụng SPA theo dõi giá crypto theo thời gian thực, kết nối trực tiếp đến Binance API qua REST API và WebSocket. Hiển thị biểu đồ nến Nhật Bản (Candlestick) + Volume với zoom/pan tương tác, hỗ trợ 8 đồng coin (BTC, ETH, SOL, DOT, BNB, LINK, CAKE, MATIC) và 7 timeframe (1m đến 1d). Tích hợp chỉ báo kỹ thuật EMA-21 và RSI-14, dark/light mode, responsive design và tự động reconnect khi mất kết nối.',
    proj_crypto_chart_tags: 'React 19 · TypeScript 5.8 · Vite 6.3 · Tailwind CSS 3.4 · lightweight-charts 4.2 · technicalindicators 3.1 · Axios · WebSocket · Binance API · TradingView',
    proj_christmas_movie_name: 'Christmas Movie Marathon Landing Page',
    proj_christmas_movie_desc: 'Landing page sự kiện xem phim Giáng sinh cho Cafe Ten Quan, cho phép người dùng xem lịch chiếu 4 bộ phim kinh điển (Die Hard, The Nightmare Before Christmas, Love Actually, Last Holiday), đăng ký vé với chọn loại ghế (Sofa/Ghế thường), đồ ăn và đồ uống. Tích hợp Google Apps Script + Google Sheets làm backend, UI festive với nhạc nền Mariah Carey và thiết kế responsive.',
    proj_christmas_movie_tags: 'React 19 · TypeScript · Vite · Tailwind CSS 3 · Google Apps Script · Google Sheets · HTML5 Audio · Responsive Design · SPA · Cafe Ten Quan · Christmas 2025',
    proj_clinic_td_name: 'Hệ Thống Quản Lý Phòng Khám T&D',
    proj_clinic_td_desc: 'Hệ thống quản lý phòng khám da liễu thẩm mỹ full-stack với React 19 + TypeScript (Frontend) và Spring Boot 3.4.2 + Java 17 (Backend). Hỗ trợ 3 vai trò: Admin, Bác sĩ, Lễ tân với workflow riêng biệt. Tính năng gồm đặt lịch hẹn online, hồ sơ bệnh án điện tử (EMR), thanh toán POS, xuất hóa đơn PDF, thống kê doanh thu với Materialized Views. Xác thực JWT với Redis token whitelist, i18n EN/VI, responsive design.',
    proj_clinic_td_tags: 'React 19 · TypeScript · Redux Toolkit · React Query · Ant Design 6 · Tailwind CSS 3 · Sass · Spring Boot 3.4 · Java 17 · PostgreSQL · Redis · JWT · i18next · Recharts · Vite · PDF Export',
    proj_industrial_park_name: 'Hệ Thống Quản Lý Cụm Công Nghiệp Phú Thọ',
    proj_industrial_park_desc: 'Ứng dụng GIS (Geographic Information System) web-based quản lý toàn diện các cụm công nghiệp tỉnh Phú Thọ. Hệ thống cung cấp bản đồ tương tác Mapbox/Leaflet, quản lý dữ liệu không gian địa lý với PostGIS, quản trị khu công nghiệp (50+ trường), đăng ký doanh nghiệp, theo dõi giấy phép, báo cáo sản lượng/lao động và giám sát môi trường. RBAC với 50+ permissions, Dashboard chuyên biệt, Form Template System.',
    proj_industrial_park_tags: 'Laravel 12 · PHP 8.2 · React 19 · TypeScript · Inertia.js 2 · PostGIS · PostgreSQL · Mapbox GL JS · Leaflet · Turf.js · Radix UI · TanStack Table · Chart.js · Docker · Redis · Laravel Sanctum',
    proj_sentinel_name: 'PROJECT_SENTINEL_V2',
    proj_sentinel_desc: 'Hệ thống giám sát hiệu năng thời gian thực với Rust, WebAssembly và gRPC. Xử lý 1M+ sự kiện/giây, latency dưới 5ms.',
    proj_sentinel_tags: 'Rust · WebAssembly · gRPC',
    proj_aether_name: 'AETHER_NEXUS',
    proj_aether_desc: 'Nền tảng API Gateway tập trung cho microservices với load balancing thông minh và rate limiting tự động.',
    proj_aether_tags: 'Go · Redis · Kubernetes',
    contact_title: 'Liên_Hệ',
    contact_subtitle: 'VỚI_TÔI',
    contact_emailLabel: 'ĐỊA_CHỈ_EMAIL',
    contact_phoneLabel: 'LIÊN_LẠC_BẢO_MẬT',
    contact_formName: 'ĐỊNH_DANH_NGƯỜI_DÙNG',
    contact_formEmail: 'ĐỊA_CHỈ_PHẢN_HỒI',
    contact_formMessage: 'DỮ_LIỆU_TRUYỀN_TẢI',
    contact_namePlaceholder: 'HỌ TÊN',
    contact_emailPlaceholder: 'EMAIL',
    contact_messagePlaceholder: 'NỘI DUNG TIN NHẮN',
    contact_submit: 'GỬI_GÓI_TIN',
    contact_sending: 'ĐANG_GỬI...',
    footer_copyright: '©2024_KINETIC_BRUTALISM_DEV.INIT()',
    footer_github: 'GITHUB',
    footer_linkedin: 'LINKEDIN',
    footer_source: 'MÃ_NGUỒN',
  },
  en: {
    navbar_home: 'HOME',
    navbar_about: 'ABOUT',
    navbar_experience: 'EXPERIENCE',
    navbar_skills: 'SKILLS',
    navbar_projects: 'PROJECTS',
    navbar_contact: 'CONNECT',
    hero_status: 'STATUS: ONLINE',
    hero_greeting: 'HELLO, I AM',
    hero_name: 'Bui Hoang Viet',
    hero_subtitle: 'Passionate Frontend Developer specializing in building modern web interfaces and seamless user experiences. Always learning new technologies to deliver quality products.',
    hero_btnProject: 'HIRE ME',
    hero_btnArsenal: 'DOWNLOAD CV',
    hero_expBadge: '8+',
    hero_expLabel: 'Years_Experience',
    hero_stat_years: 'Years_Experience',
    hero_stat_projects: 'Projects_Completed',
    hero_stat_tech: 'Technologies',
    hero_edu: 'UNETI — IT 2025',
    hero_student: 'Open to Work',
    narrative_title: 'Biography',
    about_title: 'Biography',
    about_fullname: 'Full_Name',
    about_fullname_val: 'Bui Hoang Viet',
    about_birth: 'Birthday',
    about_birth_val: '15/10/2003',
    about_university: 'University',
    about_univ_val: 'UNETI, Hanoi',
    about_gpa: 'GPA',
    about_gpa_val: '3.1 / 4.0',
    about_major: 'Major',
    about_major_val: 'Information Technology',
    about_email: 'Email',
    about_email_val: 'bhviet1510@gmail.com',
    about_phone: 'Phone',
    about_phone_val: '+84 912 687 955',
    about_location: 'Location',
    about_location_val: 'Hanoi, Vietnam',
    about_bio1: "I'm a passionate Frontend developer always seeking creative solutions for user interfaces. Proficient in Vue 3 and React to build modern, seamless web experiences.",
    about_bio2: "My goal is to continuously learn and develop professional skills to become a well-rounded Full-Stack Developer, contributing real value to the tech community.",
    about_edu_title: 'Education',
    about_school: 'University of Economics — Technology for Industries, Hanoi',
    about_major_school: 'Information Technology',
    about_goals_title: '3-Year_Goals',
    about_goal1: 'Become a professional Full-stack Developer',
    about_goal2: 'Master Cloud technologies (AWS / Azure)',
    about_goal3: 'Contribute to major Open Source projects',
    about_goal4: 'Build tech products that benefit the community',
    narrative_edu_label: 'SYSTEM_INITIALIZATION',
    narrative_edu_school: 'Hanoi University of Science and Technology',
    narrative_edu_period: '2014 — 2019',
    narrative_edu_degree: 'Bachelor of Computer Science',
    narrative_edu_gpa_label: 'GPA',
    narrative_edu_gpa: '3.8 / 4.0',
    narrative_career_section_title: 'Career_Summary',
    narrative_career_label: 'CAREER_TRAJECTORY',
    narrative_current_period: '2021 — PRESENT',
    narrative_current_title: 'Lead System Architect',
    narrative_current_summary: 'Designing fault-tolerant microservices architectures and leading core infrastructure scaling initiatives for Fintech platforms.',
    narrative_past_period: '2019 — 2021',
    narrative_past_title: 'Full-Stack Engineer',
    narrative_past_summary: 'Developing complex enterprise dashboards and high-performance APIs using the T3 stack and edge computing.',
    narrative_career_summary: '8 years building systems from microservices to monoliths. From intern at VNG to Lead System Architect at Monolith Systems JSC.',
    exp_title: 'Professional_Experience',
    exp_current: 'Present',
    exp_role1_company: 'TD Clinic',
    exp_role1_title: 'Freelance Frontend Developer',
    exp_role1_period: '02/2026 — 04/2026',
    exp_role1_task1: 'Built complete frontend system with React, TypeScript using module-based architecture.',
    exp_role1_task2: 'Implemented role-based access control and protected routes with React Router.',
    exp_role1_task3: 'Built authentication and session management when working with APIs.',
    exp_role1_task4: 'Developed appointment booking system with time slots, supporting multiple doctors and reducing schedule conflicts.',
    exp_role1_task5: 'Managed global state with Redux Toolkit to ensure data consistency.',
    exp_role1_task6: 'Built reusable components (Table, Modal, Pagination...).',
    exp_role1_task7: 'Integrated RESTful APIs with Axios, handling loading and error states.',
    exp_role1_task8: 'Built UI with Tailwind CSS and Ant Design.',
    exp_role1_task9: 'Displayed data using charts with Recharts.',
    exp_role1_task10: 'Supported multi-language with i18next.',
    exp_role1_task11: 'Optimized performance with lazy loading, code splitting.',
    exp_role1_task12: 'Deployed applications with Docker and Nginx.',
    exp_role2_company: 'SmartOSC',
    exp_role2_title: 'Intern Front-end',
    exp_role2_period: '09/2025 — 11/2025',
    exp_role2_task1: 'Participated in SPA development projects using Vue 3 + TypeScript.',
    exp_role2_task2: 'Used Pinia for centralized state management, optimizing performance and data reusability.',
    exp_role2_task3: 'Implemented Composition API, extracting logic into composable and utils files for reusability.',
    exp_role2_task4: 'Called and processed RESTful APIs via Axios, synchronized data with backend.',
    exp_role2_task5: 'Wrote reusable components, applying best practices for props, emits, lifecycle hooks.',
    exp_role2_task6: 'Learned and practiced professional teamwork workflows with Git (branching, merge, pull request).',
    exp_role2_task7: 'Implemented responsive UI from Figma designs, ensuring cross-device compatibility.',
    exp_role2_task8: 'Trained and worked with Laravel Backend in real projects.',
    exp_role3_company: 'Mattech',
    exp_role3_title: 'Intern Front-end',
    exp_role3_period: '11/2024 — 05/2025',
    exp_role3_task1: 'Developed and modified website interfaces using React TypeScript with reusable components.',
    exp_role3_task2: 'Designed responsive interfaces on multiple devices with Tailwind CSS.',
    exp_role3_task3: 'Managed source code with Git & GitLab, performed merge/pull requests, code reviews.',
    exp_role3_task4: 'Trained on Backend (Laravel PHP), worked with real APIs.',
    exp_role3_task5: 'Applied React Hooks (useState, useEffect, useMemo, useContext) for logic processing and performance optimization.',
    exp_role3_task6: 'Integrated RESTful APIs with Axios, handling loading and error states.',
    skill_title: 'Skills',
    skill_fe: '01. FRONTEND',
    skill_be: '02. BACKEND',
    skill_ui: '03. UI_LIBRARIES',
    skill_tools: '04. TOOLS',
    proj_title: 'Project_Archive',
    proj_deployed: 'DEPLOYED',
    proj_beta: 'BETA',
    proj_crypto_chart_name: 'Crypto Real-time Chart Dashboard',
    proj_crypto_chart_desc: 'SPA for real-time crypto price tracking, connecting directly to Binance API via REST API and WebSocket. Displays interactive Japanese Candlestick + Volume charts with zoom/pan support, supports 8 coins (BTC, ETH, SOL, DOT, BNB, LINK, CAKE, MATIC) and 7 timeframes (1m to 1d). Integrates EMA-21 and RSI-14 technical indicators, dark/light mode, responsive design and auto-reconnect on connection loss.',
    proj_crypto_chart_tags: 'React 19 · TypeScript 5.8 · Vite 6.3 · Tailwind CSS 3.4 · lightweight-charts 4.2 · technicalindicators 3.1 · Axios · WebSocket · Binance API · TradingView',
    proj_christmas_movie_name: 'Christmas Movie Marathon Landing Page',
    proj_christmas_movie_desc: 'Christmas movie event landing page for Cafe Ten Quan, allowing users to view schedules for 4 classic films (Die Hard, The Nightmare Before Christmas, Love Actually, Last Holiday), register tickets with seat selection (Sofa/Regular), food and drinks. Integrates Google Apps Script + Google Sheets as backend, festive UI with Mariah Carey background music and responsive design.',
    proj_christmas_movie_tags: 'React 19 · TypeScript · Vite · Tailwind CSS 3 · Google Apps Script · Google Sheets · HTML5 Audio · Responsive Design · SPA · Cafe Ten Quan · Christmas 2025',
    proj_clinic_td_name: 'T&D Clinic Management System',
    proj_clinic_td_desc: 'Full-stack dermatology & aesthetic clinic management system built with React 19 + TypeScript (Frontend) and Spring Boot 3.4.2 + Java 17 (Backend). Supports 3 roles: Admin, Doctor, Receptionist with distinct workflows. Features include online appointment booking, electronic medical records (EMR), POS billing, PDF invoice export, and revenue statistics with Materialized Views. JWT authentication with Redis token whitelist, i18n EN/VI, responsive design.',
    proj_clinic_td_tags: 'React 19 · TypeScript · Redux Toolkit · React Query · Ant Design 6 · Tailwind CSS 3 · Sass · Spring Boot 3.4 · Java 17 · PostgreSQL · Redis · JWT · i18next · Recharts · Vite · PDF Export',
    proj_industrial_park_name: 'Phú Thọ Industrial Park Management System',
    proj_industrial_park_desc: 'GIS (Geographic Information System) web-based application for comprehensive management of industrial zones in Phú Thọ province, Vietnam. System provides interactive maps with Mapbox/Leaflet, PostGIS spatial data management, industrial zone administration (50+ fields), company registration, permit tracking, production/labor reports and environmental monitoring. RBAC with 50+ permissions, specialized Dashboards, Form Template System.',
    proj_industrial_park_tags: 'Laravel 12 · PHP 8.2 · React 19 · TypeScript · Inertia.js 2 · PostGIS · PostgreSQL · Mapbox GL JS · Leaflet · Turf.js · Radix UI · TanStack Table · Chart.js · Docker · Redis · Laravel Sanctum',
    proj_sentinel_name: 'PROJECT_SENTINEL_V2',
    proj_sentinel_desc: 'Real-time performance monitoring system with Rust, WebAssembly and gRPC. Processing 1M+ events/second with sub-5ms latency.',
    proj_sentinel_tags: 'Rust · WebAssembly · gRPC',
    proj_aether_name: 'AETHER_NEXUS',
    proj_aether_desc: 'Centralized API gateway platform for microservices with intelligent load balancing and automatic rate limiting.',
    proj_aether_tags: 'Go · Redis · Kubernetes',
    proj_ecommerce_name: 'Sàn TMĐT',
    proj_ecommerce_desc: 'Website thương mại điện tử full chức năng, hỗ trợ giỏ hàng, thanh toán và quản lý sản phẩm.',
    proj_ecommerce_tags: 'Vue · Node.js · PostgreSQL',
    proj_fitapp_name: 'App Theo Dõi Tập Luyện',
    proj_fitapp_desc: 'Ứng dụng quản lý fitness, theo dõi lịch tập và dinh dưỡng hàng ngày trên thiết bị di động.',
    proj_fitapp_tags: 'React Native · Firebase',
    proj_corpweb_name: 'Website Doanh Nghiệp',
    proj_corpweb_desc: 'Landing page hiện đại cho doanh nghiệp, tối ưu SEO và responsive trên mọi thiết bị.',
    proj_corpweb_tags: 'React · Next.js · Tailwind',
    contact_title: 'Liên_Hệ',
    contact_subtitle: 'WITH_ME',
    contact_emailLabel: 'EMAIL_ADDRESS',
    contact_phoneLabel: 'SECURE_CONTACT',
    contact_formName: 'USER_IDENTIFIER',
    contact_formEmail: 'REPLY_ADDRESS',
    contact_formMessage: 'TRANSMISSION_DATA',
    contact_namePlaceholder: 'FULL NAME',
    contact_emailPlaceholder: 'EMAIL',
    contact_messagePlaceholder: 'YOUR MESSAGE',
    contact_submit: 'SEND_PACKET',
    contact_sending: 'SENDING...',
    footer_copyright: '©2024_KINETIC_BRUTALISM_DEV.INIT()',
    footer_github: 'GITHUB',
    footer_linkedin: 'LINKEDIN',
    footer_source: 'SOURCE',
  },
} as const;

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'vi';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const t = (key: string): string => {
    return (translations[lang] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
