import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';
import type { Language } from '../types';

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TransKey) => string;
}

export type TransKey = keyof typeof translations.vi;

const translations = {
  vi: {
    navbar_home: 'Trang_Chủ',
    navbar_about: 'Giới_Thiệu',
    navbar_experience: 'Kinh_Nghiệm',
    navbar_skills: 'Kỹ_Năng',
    navbar_projects: 'Dự_Án',
    navbar_contact: 'Liên_Hệ',
    hero_status: 'TRẠNG_THÁI: TRỰC_TUYẾN',
    hero_greeting: 'XIN CHÀO, TÔI LÀ',
    hero_name: 'Bùi Hoàng Việt',
    hero_subtitle: 'Lập trình viên Frontend đầy đam mê, chuyên xây dựng giao diện web hiện đại và trải nghiệm người dùng mượt mà. Luôn học hỏi công nghệ mới để tạo ra những sản phẩm chất lượng.',
    hero_btnProject: 'THUÊ TÔI',
    hero_btnArsenal: 'TẢI CV',
    hero_expBadge: '8+',
    hero_expLabel: 'Năm_Kinh_Nghiệm',
    hero_stat_years: 'Năm_Kinh_Nghiệm',
    hero_stat_projects: 'Dự_Án_Hoàn_Thành',
    hero_stat_tech: 'Công_Nghệ_Sử_Dụng',
    hero_edu: 'HUST — CS 2025',
    hero_student: 'Đang tìm việc',
    narrative_title: 'Tiểu_Sử',
    about_title: 'Tiểu_Sử',
    about_fullname: 'Họ_tên',
    about_fullname_val: 'Bùi Hoàng Việt',
    about_birth: 'Năm_sinh',
    about_birth_val: '15/10/2003',
    about_university: 'Trường',
    about_univ_val: 'ĐH KT-KTCN Hà Nội',
    about_gpa: 'GPA',
    about_gpa_val: '3.1 / 4.0',
    about_major: 'Ngành',
    about_major_val: 'Công nghệ Thông tin',
    about_email: 'Email',
    about_email_val: 'bhviet1510@gmail.com',
    about_phone: 'SĐT',
    about_phone_val: '+84 912 687 955',
    about_location: 'Địa_chỉ',
    about_location_val: 'Hà Nội, Việt Nam',
    about_bio1: 'Tôi là một lập trình viên Frontend đầy đam mê, luôn tìm kiếm những giải pháp sáng tạo cho giao diện người dùng. Thành thạo Vue 3 và React để xây dựng những trải nghiệm web hiện đại, mượt mà.',
    about_bio2: 'Mục tiêu của tôi là không ngừng học hỏi, phát triển kỹ năng chuyên môn để trở thành một Full-Stack Developer toàn diện, đóng góp giá trị thực sự cho cộng đồng công nghệ.',
    about_edu_title: 'Học_Vấn',
    about_school: 'Đại học Kinh tế — Kỹ thuật Công nghiệp Hà Nội',
    about_major_school: 'Công nghệ Thông tin',
    about_goals_title: 'Mục_Tiêu_3_Năm',
    about_goal1: 'Trở thành Full-stack Developer chuyên nghiệp',
    about_goal2: 'Nắm vững các công nghệ Cloud (AWS / Azure)',
    about_goal3: 'Đóng góp cho các dự án Open Source lớn',
    about_goal4: 'Xây dựng sản phẩm công nghệ có ích cho cộng đồng',
    narrative_edu_section_title: 'Hồ_Sơ_Học_Vấn',
    narrative_edu_label: 'HỆ_THỐNG_KHỞI_TẠO',
    narrative_edu_school: 'Đại học Bách Khoa Hà Nội',
    narrative_edu_period: '2014 — 2019',
    narrative_edu_degree: 'Cử nhân Khoa học Máy tính',
    narrative_edu_gpa_label: 'Điểm trung bình (GPA)',
    narrative_edu_gpa: '3.8 / 4.0',
    narrative_career_section_title: 'Tóm_Tắt_Nghề_Nghiệp',
    narrative_career_label: 'HÀNH_TRÌNH_CÔNG_NGHỆ',
    narrative_current_period: '2021 — HIỆN TẠI',
    narrative_current_title: 'Kiến trúc sư hệ thống chính',
    narrative_current_summary: 'Thiết kế các kiến trúc microservices có khả năng chịu lỗi cao và dẫn dắt các sáng kiến mở rộng cơ sở hạ tầng cốt lõi cho các nền tảng Fintech.',
    narrative_past_period: '2019 — 2021',
    narrative_past_title: 'Kỹ sư Full-Stack',
    narrative_past_summary: 'Phát triển các bảng điều khiển doanh nghiệp phức tạp và các API hiệu suất cao sử dụng T3 stack và tính toán tại biên (edge computing).',
    narrative_career_summary: '8 năm kiến tạo hệ thống từ kiến trúc vi mô đến nguyên khối. Từ thực tập sinh tại VNG đến Lead System Architect tại Monolith Systems JSC.',
    exp_title: 'Kinh_Nghiệm_Chuyên_Môn',
    exp_current: 'Hiện Tại',
    exp_role1_company: 'Công Ty TNHH ABC',
    exp_role1_title: 'Fresher Frontend Developer',
    exp_role1_period: '2024 — NAY',
    exp_role1_task1: 'Phát triển và bảo trì các tính năng giao diện người dùng cho ứng dụng web sử dụng Vue 3 và Tailwind CSS.',
    exp_role1_task2: 'Tối ưu hiệu năng giao diện, giảm thời gian tải trang xuống 40% thông qua lazy-loading và code-splitting.',
    exp_role1_task3: 'Tham gia xây dựng và chuẩn hóa Design System nội bộ, tái sử dụng component trên 5 dự án khác nhau.',
    exp_role2_company: 'Freelance / Dự án cá nhân',
    exp_role2_title: 'Lập trình viên Frontend (Freelance)',
    exp_role2_period: '2023 — 2024',
    exp_role2_task1: 'Nhận việc freelance xây dựng landing page và website thương mại điện tử cho khách hàng trong nước.',
    exp_role2_task2: 'Sử dụng React và Next.js để phát triển giao diện responsive, tương thích đa trình duyệt và thiết bị di động.',
    exp_role2_task3: 'Quản lý và triển khai dự án độc lập từ giai đoạn thiết kế đến deploy lên Vercel và Netlify.',
    exp_role3_company: 'Trường ĐH Kinh tế — Kỹ thuật Công nghiệp',
    exp_role3_title: 'Sinh viên ngành Công nghệ Thông tin',
    exp_role3_period: '2021 — 2025',
    exp_role3_task1: 'Tốt nghiệp chuyên ngành CNTT với GPA 3.2/4.0, hoàn thành các đồ án môn học về phát triển web và ứng dụng di động.',
    exp_role3_task2: 'Tham gia các dự án nhóm xây dựng ứng dụng web sử dụng React và Node.js, đạt điểm A trên các môn học chuyên ngành.',
    exp_role3_task3: 'Tự học và cập nhật các công nghệ mới như TypeScript, Vite, và các framework CSS hiện đại.',
    skill_title: 'Kỹ_Năng',
    skill_fe: '01. FRONTEND',
    skill_be: '02. BACKEND',
    skill_ui: '03. UI_LIBRARIES',
    skill_tools: '04. TOOLS',
    proj_title: 'Dự_Án_Triển_Khai',
    proj_deployed: 'ĐÃ_TRIỂN_KHAI',
    proj_beta: 'BẢN_THỬ_NGHIỆM',
    proj_sentinel_name: 'PROJECT_SENTINEL_V2',
    proj_sentinel_desc: 'Hệ thống giám sát hiệu năng thời gian thực với Rust, WebAssembly và gRPC. Xử lý 1M+ sự kiện/giây, latency dưới 5ms.',
    proj_sentinel_tags: 'Rust · WebAssembly · gRPC',
    proj_aether_name: 'AETHER_NEXUS',
    proj_aether_desc: 'Nền tảng API Gateway tập trung cho microservices với load balancing thông minh và rate limiting tự động.',
    proj_aether_tags: 'Go · Redis · Kubernetes',
    contact_title: 'Liên_Hệ',
    contact_subtitle: 'VỚI_TÔI',
    contact_emailLabel: 'ĐỊA_CHỈ_EMAIL',
    contact_phoneLabel: 'LIÊN_LẠC_BẢO_MẬT',
    contact_formName: 'ĐỊNH_DANH_NGƯỜI_DÙNG',
    contact_formEmail: 'ĐỊA_CHỈ_PHẢN_HỒI',
    contact_formMessage: 'DỮ_LIỆU_TRUYỀN_TẢI',
    contact_namePlaceholder: 'HỌ TÊN',
    contact_emailPlaceholder: 'EMAIL',
    contact_messagePlaceholder: 'NỘI DUNG TIN NHẮN',
    contact_submit: 'GỬI_GÓI_TIN',
    contact_sending: 'ĐANG_GỬI...',
    footer_copyright: '©2024_KINETIC_BRUTALISM_DEV.INIT()',
    footer_github: 'GITHUB',
    footer_linkedin: 'LINKEDIN',
    footer_source: 'MÃ_NGUỒN',
  },
  en: {
    navbar_home: 'HOME',
    navbar_about: 'ABOUT',
    navbar_experience: 'EXPERIENCE',
    navbar_skills: 'SKILLS',
    navbar_projects: 'PROJECTS',
    navbar_contact: 'CONNECT',
    hero_status: 'STATUS: ONLINE',
    hero_greeting: 'HELLO, I AM',
    hero_name: 'Bui Hoang Viet',
    hero_subtitle: 'Passionate Frontend Developer specializing in building modern web interfaces and seamless user experiences. Always learning new technologies to deliver quality products.',
    hero_btnProject: 'HIRE ME',
    hero_btnArsenal: 'DOWNLOAD CV',
    hero_expBadge: '8+',
    hero_expLabel: 'Years_Experience',
    hero_stat_years: 'Years_Experience',
    hero_stat_projects: 'Projects_Completed',
    hero_stat_tech: 'Technologies',
    hero_edu: 'UNETI — IT 2025',
    hero_student: 'Open to Work',
    narrative_title: 'Biography',
    about_title: 'Biography',
    about_fullname: 'Full_Name',
    about_fullname_val: 'Bui Hoang Viet',
    about_birth: 'Birthday',
    about_birth_val: '15/10/2003',
    about_university: 'University',
    about_univ_val: 'UNETI, Hanoi',
    about_gpa: 'GPA',
    about_gpa_val: '3.1 / 4.0',
    about_major: 'Major',
    about_major_val: 'Information Technology',
    about_email: 'Email',
    about_email_val: 'bhviet1510@gmail.com',
    about_phone: 'Phone',
    about_phone_val: '+84 912 687 955',
    about_location: 'Location',
    about_location_val: 'Hanoi, Vietnam',
    about_bio1: "I'm a passionate Frontend developer always seeking creative solutions for user interfaces. Proficient in Vue 3 and React to build modern, seamless web experiences.",
    about_bio2: "My goal is to continuously learn and develop professional skills to become a well-rounded Full-Stack Developer, contributing real value to the tech community.",
    about_edu_title: 'Education',
    about_school: 'University of Economics — Technology for Industries, Hanoi',
    about_major_school: 'Information Technology',
    about_goals_title: '3-Year_Goals',
    about_goal1: 'Become a professional Full-stack Developer',
    about_goal2: 'Master Cloud technologies (AWS / Azure)',
    about_goal3: 'Contribute to major Open Source projects',
    about_goal4: 'Build tech products that benefit the community',
    narrative_edu_label: 'SYSTEM_INITIALIZATION',
    narrative_edu_school: 'Hanoi University of Science and Technology',
    narrative_edu_period: '2014 — 2019',
    narrative_edu_degree: 'Bachelor of Computer Science',
    narrative_edu_gpa_label: 'GPA',
    narrative_edu_gpa: '3.8 / 4.0',
    narrative_career_section_title: 'Career_Summary',
    narrative_career_label: 'CAREER_TRAJECTORY',
    narrative_current_period: '2021 — PRESENT',
    narrative_current_title: 'Lead System Architect',
    narrative_current_summary: 'Designing fault-tolerant microservices architectures and leading core infrastructure scaling initiatives for Fintech platforms.',
    narrative_past_period: '2019 — 2021',
    narrative_past_title: 'Full-Stack Engineer',
    narrative_past_summary: 'Developing complex enterprise dashboards and high-performance APIs using the T3 stack and edge computing.',
    narrative_career_summary: '8 years building systems from microservices to monoliths. From intern at VNG to Lead System Architect at Monolith Systems JSC.',
    exp_title: 'Professional_Experience',
    exp_current: 'Present',
    exp_role1_company: 'ABC Tech Co., Ltd.',
    exp_role1_title: 'Fresher Frontend Developer',
    exp_role1_period: '2024 — NOW',
    exp_role1_task1: 'Developed and maintained UI features for web applications using Vue 3 and Tailwind CSS.',
    exp_role1_task2: 'Optimized frontend performance, reducing page load time by 40% through lazy-loading and code-splitting.',
    exp_role1_task3: 'Contributed to building and standardizing internal Design System, reusing components across 5 different projects.',
    exp_role2_company: 'Freelance / Personal Projects',
    exp_role2_title: 'Frontend Developer (Freelance)',
    exp_role2_period: '2023 — 2024',
    exp_role2_task1: 'Built landing pages and e-commerce websites for local clients as a freelance developer.',
    exp_role2_task2: 'Used React and Next.js to develop responsive interfaces compatible with all browsers and mobile devices.',
    exp_role2_task3: 'Managed and deployed projects independently from design phase through deployment on Vercel and Netlify.',
    exp_role3_company: 'University of Economics — Technology for Industries',
    exp_role3_title: 'IT Student',
    exp_role3_period: '2021 — 2025',
    exp_role3_task1: 'Graduated in IT with GPA 3.2/4.0, completed course projects on web development and mobile applications.',
    exp_role3_task2: 'Participated in team projects building web applications using React and Node.js, achieving A grades in major courses.',
    exp_role3_task3: 'Self-learned and kept up with new technologies such as TypeScript, Vite, and modern CSS frameworks.',
    skill_title: 'Skills',
    skill_fe: '01. FRONTEND',
    skill_be: '02. BACKEND',
    skill_ui: '03. UI_LIBRARIES',
    skill_tools: '04. TOOLS',
    proj_title: 'Project_Archive',
    proj_deployed: 'DEPLOYED',
    proj_beta: 'BETA',
    proj_sentinel_name: 'PROJECT_SENTINEL_V2',
    proj_sentinel_desc: 'Real-time performance monitoring system with Rust, WebAssembly and gRPC. Processing 1M+ events/second with sub-5ms latency.',
    proj_sentinel_tags: 'Rust · WebAssembly · gRPC',
    proj_aether_name: 'AETHER_NEXUS',
    proj_aether_desc: 'Centralized API gateway platform for microservices with intelligent load balancing and automatic rate limiting.',
    proj_aether_tags: 'Go · Redis · Kubernetes',
    proj_ecommerce_name: 'Sàn TMĐT',
    proj_ecommerce_desc: 'Website thương mại điện tử full chức năng, hỗ trợ giỏ hàng, thanh toán và quản lý sản phẩm.',
    proj_ecommerce_tags: 'Vue · Node.js · PostgreSQL',
    proj_fitapp_name: 'App Theo Dõi Tập Luyện',
    proj_fitapp_desc: 'Ứng dụng quản lý fitness, theo dõi lịch tập và dinh dưỡng hàng ngày trên thiết bị di động.',
    proj_fitapp_tags: 'React Native · Firebase',
    proj_corpweb_name: 'Website Doanh Nghiệp',
    proj_corpweb_desc: 'Landing page hiện đại cho doanh nghiệp, tối ưu SEO và responsive trên mọi thiết bị.',
    proj_corpweb_tags: 'React · Next.js · Tailwind',
    contact_title: 'Liên_Hệ',
    contact_subtitle: 'WITH_ME',
    contact_emailLabel: 'EMAIL_ADDRESS',
    contact_phoneLabel: 'SECURE_CONTACT',
    contact_formName: 'USER_IDENTIFIER',
    contact_formEmail: 'REPLY_ADDRESS',
    contact_formMessage: 'TRANSMISSION_DATA',
    contact_namePlaceholder: 'FULL NAME',
    contact_emailPlaceholder: 'EMAIL',
    contact_messagePlaceholder: 'YOUR MESSAGE',
    contact_submit: 'SEND_PACKET',
    contact_sending: 'SENDING...',
    footer_copyright: '©2024_KINETIC_BRUTALISM_DEV.INIT()',
    footer_github: 'GITHUB',
    footer_linkedin: 'LINKEDIN',
    footer_source: 'SOURCE',
  },
} as const;

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'vi';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const t = (key: string): string => {
    return (translations[lang] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
