import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';
import type { Language } from '../types';

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TransKey) => string;
}

export type TransKey = keyof typeof translations.vi;

const translations = {
  vi: {
    navbar_home: 'Trang_Chủ',
    navbar_about: 'Giới_Thiệu',
    navbar_experience: 'Kinh_Nghiệm',
    navbar_skills: 'Kỹ_Năng',
    navbar_projects: 'Dự_Án',
    navbar_contact: 'Liên_Hệ',
    hero_status: 'TRẠNG_THÁI: TRỰC_TUYẾN',
    hero_greeting: 'XIN CHÀO, TÔI LÀ',
    hero_name: 'Bùi Hoàng Việt',
    hero_subtitle: 'Lập trình viên Frontend đầy đam mê, chuyên xây dựng giao diện web hiện đại và trải nghiệm người dùng mượt mà. Luôn học hỏi công nghệ mới để tạo ra những sản phẩm chất lượng.',
    hero_btnProject: 'THUÊ TÔI',
    hero_btnArsenal: 'TẢI CV',
    hero_expBadge: '8+',
    hero_expLabel: 'Năm_Kinh_Nghiệm',
    hero_stat_years: 'Năm_Kinh_Nghiệm',
    hero_stat_projects: 'Dự_Án_Hoàn_Thành',
    hero_stat_tech: 'Công_Nghệ_Sử_Dụng',
    hero_edu: 'HUST — CS 2025',
    hero_student: 'Đang tìm việc',
    narrative_title: 'Tiểu_Sử',
    about_title: 'Tiểu_Sử',
    about_fullname: 'Họ_tên',
    about_fullname_val: 'Bùi Hoàng Việt',
    about_birth: 'Năm_sinh',
    about_birth_val: '15/10/2003',
    about_university: 'Trường',
    about_univ_val: 'ĐH KT-KTCN Hà Nội',
    about_gpa: 'GPA',
    about_gpa_val: '3.1 / 4.0',
    about_major: 'Ngành',
    about_major_val: 'Công nghệ Thông tin',
    about_email: 'Email',
    about_email_val: 'bhviet1510@gmail.com',
    about_phone: 'SĐT',
    about_phone_val: '+84 912 687 955',
    about_location: 'Địa_chỉ',
    about_location_val: 'Hà Nội, Việt Nam',
    about_bio1: 'Tôi là một lập trình viên Frontend đầy đam mê, luôn tìm kiếm những giải pháp sáng tạo cho giao diện người dùng. Thành thạo Vue 3 và React để xây dựng những trải nghiệm web hiện đại, mượt mà.',
    about_bio2: 'Mục tiêu của tôi là không ngừng học hỏi, phát triển kỹ năng chuyên môn để trở thành một Full-Stack Developer toàn diện, đóng góp giá trị thực sự cho cộng đồng công nghệ.',
    about_edu_title: 'Học_Vấn',
    about_school: 'Đại học Kinh tế — Kỹ thuật Công nghiệp Hà Nội',
    about_major_school: 'Công nghệ Thông tin',
    about_goals_title: 'Mục_Tiêu_3_Năm',
    about_goal1: 'Trở thành Full-stack Developer chuyên nghiệp',
    about_goal2: 'Nắm vững các công nghệ Cloud (AWS / Azure)',
    about_goal3: 'Đóng góp cho các dự án Open Source lớn',
    about_goal4: 'Xây dựng sản phẩm công nghệ có ích cho cộng đồng',
    narrative_edu_section_title: 'Hồ_Sơ_Học_Vấn',
    narrative_edu_label: 'HỆ_THỐNG_KHỞI_TẠO',
    narrative_edu_school: 'Đại học Bách Khoa Hà Nội',
    narrative_edu_period: '2014 — 2019',
    narrative_edu_degree: 'Cử nhân Khoa học Máy tính',
    narrative_edu_gpa_label: 'Điểm trung bình (GPA)',
    narrative_edu_gpa: '3.8 / 4.0',
    narrative_career_section_title: 'Tóm_Tắt_Nghề_Nghiệp',
    narrative_career_label: 'HÀNH_TRÌNH_CÔNG_NGHỆ',
    narrative_current_period: '2021 — HIỆN TẠI',
    narrative_current_title: 'Kiến trúc sư hệ thống chính',
    narrative_current_summary: 'Thiết kế các kiến trúc microservices có khả năng chịu lỗi cao và dẫn dắt các sáng kiến mở rộng cơ sở hạ tầng cốt lõi cho các nền tảng Fintech.',
    narrative_past_period: '2019 — 2021',
    narrative_past_title: 'Kỹ sư Full-Stack',
    narrative_past_summary: 'Phát triển các bảng điều khiển doanh nghiệp phức tạp và các API hiệu suất cao sử dụng T3 stack và tính toán tại biên (edge computing).',
    narrative_career_summary: '8 năm kiến tạo hệ thống từ kiến trúc vi mô đến nguyên khối. Từ thực tập sinh tại VNG đến Lead System Architect tại Monolith Systems JSC.',
    exp_title: 'Kinh_Nghiệm_Chuyên_Môn',
    exp_current: 'Hiện Tại',
    exp_role1_company: 'SmartOSC',
    exp_role1_title: 'Frontend Developer Intern',
    exp_role1_period: '09/2025 — 11/2025',
    exp_role1_task1: 'Phát triển và bảo trì SPA bằng Vue 3 và TypeScript, đảm bảo tính mở rộng và dễ bảo trì.',
    exp_role1_task2: 'Áp dụng Composition API để modularize logic nghiệp vụ thành các composables có thể tái sử dụng.',
    exp_role1_task3: 'Quản lý global state bằng Pinia, tối ưu hiệu năng và đảm bảo luồng dữ liệu nhất quán.',
    exp_role1_task4: 'Tích hợp RESTful APIs bằng Axios với xử lý async, loading và error state đúng cách.',
    exp_role1_task5: 'Xây dựng UI components có thể tái sử dụng theo best practices (props, emits, lifecycle hooks).',
    exp_role1_task6: 'Làm việc nhóm với Git workflows (branching, pull requests, code reviews).',
    exp_role1_task7: 'Implement responsive UI từ Figma designs, đảm bảo tương thích đa thiết bị.',
    exp_role2_company: 'Mattech',
    exp_role2_title: 'Frontend Developer Intern',
    exp_role2_period: '11/2024 — 05/2025',
    exp_role2_task1: 'Phát triển và nâng cao giao diện web bằng React và TypeScript với kiến trúc component tái sử dụng.',
    exp_role2_task2: 'Implement responsive và user-friendly UI bằng Tailwind CSS trên nhiều thiết bị.',
    exp_role2_task3: 'Áp dụng React Hooks (useState, useEffect, useMemo, useContext) để quản lý state và tối ưu hiệu năng.',
    exp_role2_task4: 'Tích hợp RESTful APIs bằng Axios và đảm bảo đồng bộ dữ liệu đáng tin cậy với backend.',
    exp_role2_task5: 'Phối hợp với backend developers (Laravel) để align API structure và cải thiện hiệu quả xử lý dữ liệu.',
    exp_role2_task6: 'Quản lý source code với GitLab, tham gia merge requests và code reviews.',
    exp_role2_task7: 'Đóng góp trong giai đoạn phát triển chính (02/2025 — 04/2025), tập trung vào UI và API integration.',
    exp_role3_company: 'TD Clinic',
    exp_role3_title: 'Freelance Frontend Developer',
    exp_role3_period: '02/2025 — 04/2025',
    exp_role3_task1: 'Phát triển độc lập nền tảng web cho phòng khám gồm website công khai và multi-role dashboards (Admin, Doctor, Receptionist).',
    exp_role3_task2: 'Implement role-based authentication và protected routing, đảm bảo kiểm soát truy cập an toàn.',
    exp_role3_task3: 'Xây dựng hệ thống đặt lịch khám hoàn chỉnh với chọn khung giờ, phân công bác sĩ và lịch ca làm việc.',
    exp_role3_task4: 'Phát triển UI components có thể tái sử dụng (DataTable, Modal, Pagination, FilterBar, StatsCard), giảm code trùng lặp.',
    exp_role3_task5: 'Tích hợp RESTful APIs bằng Axios và quản lý global state với Redux Toolkit.',
    exp_role3_task6: 'Implement data visualization dashboards (doanh thu, lịch hẹn, người dùng) bằng charts để giám sát thời gian thực.',
    exp_role3_task7: 'Áp dụng i18next cho hỗ trợ Tiếng Việt và Tiếng Anh.',
    exp_role3_task8: 'Tối ưu hiệu năng bằng lazy loading và code splitting; hỗ trợ responsive design và dark mode.',
    exp_role3_task9: 'Deploy ứng dụng bằng Docker và Nginx trong môi trường production-like.',
    skill_title: 'Kỹ_Năng',
    skill_fe: '01. FRONTEND',
    skill_be: '02. BACKEND',
    skill_ui: '03. UI_LIBRARIES',
    skill_tools: '04. TOOLS',
    proj_title: 'Dự_Án_Triển_Khai',
    proj_deployed: 'ĐÃ_TRIỂN_KHAI',
    proj_beta: 'BẢN_THỬ_NGHIỆM',
    proj_crypto_chart_name: 'Crypto Real-time Chart Dashboard',
    proj_crypto_chart_desc: 'Ứng dụng dashboard biểu đồ giao dịch tiền mã hóa thời gian thực, sử dụng WebSocket để stream dữ liệu nến (OHLCV) trực tiếp từ Binance với độ trễ thấp. Hỗ trợ nhiều cặp coin và timeframe, hiển thị biểu đồ candlestick + volume bằng lightweight-charts, tích hợp các chỉ báo kỹ thuật (EMA, RSI), dark/light mode và cập nhật dữ liệu liên tục mà không cần reload trang.',
    proj_crypto_chart_tags: 'React 19 · TypeScript · Vite · Tailwind CSS · WebSocket · lightweight-charts · technicalindicators · Axios · Real-time Data · Financial Dashboard',
    proj_christmas_movie_name: 'Christmas Movie Marathon Landing Page',
    proj_christmas_movie_desc: 'Landing page sự kiện xem phim Giáng sinh được xây dựng bằng React + TypeScript, cho phép người dùng xem lịch chiếu, chọn phim và đăng ký vé với tính năng chọn số lượng, kiểm tra số ghế còn lại và tính giá theo thời gian thực. Tích hợp Google Sheets làm backend để lưu dữ liệu đăng ký, kết hợp UI festive với nhạc nền, modal nhiều lớp và thiết kế responsive.',
    proj_christmas_movie_tags: 'React 19 · TypeScript · Vite · Tailwind CSS · Google Sheets API · HTML5 Audio · Responsive Design · SPA · Event Landing Page',
    proj_clinic_td_name: 'Hệ_Thống_Quản_Lý_Phòng_Khám_T&D',
    proj_clinic_td_desc: 'Xây dựng nền tảng quản lý phòng khám đa vai trò với workflow hoàn toàn riêng biệt cho Admin, Lễ tân và Bác sĩ. Thiết kế hệ thống DataTable kiểu an toàn và có thể tái sử dụng với cột có thể cấu hình, phân trang và CRUD modals để chuẩn hóa xử lý dữ liệu toàn ứng dụng. Xây dựng các tính năng hồ sơ y khoa nâng cao bao gồm trình tạo đơn thuốc động, theo dõi tiến độ điều trị và quản lý hình ảnh trước/sau. Triển khai xác thực dựa trên vai trò với routing được bảo vệ và state tập trung sử dụng Redux Toolkit, cùng hệ thống i18n hoàn chỉnh (EN/VI) cho bản địa hóa.',
    proj_clinic_td_tags: 'React 19 · TypeScript · Redux Toolkit · React Router · Tailwind CSS · SCSS · Ant Design · Axios · i18next · Role-Based Architecture · Reusable Components · Vite',
    proj_sentinel_name: 'PROJECT_SENTINEL_V2',
    proj_sentinel_desc: 'Hệ thống giám sát hiệu năng thời gian thực với Rust, WebAssembly và gRPC. Xử lý 1M+ sự kiện/giây, latency dưới 5ms.',
    proj_sentinel_tags: 'Rust · WebAssembly · gRPC',
    proj_aether_name: 'AETHER_NEXUS',
    proj_aether_desc: 'Nền tảng API Gateway tập trung cho microservices với load balancing thông minh và rate limiting tự động.',
    proj_aether_tags: 'Go · Redis · Kubernetes',
    contact_title: 'Liên_Hệ',
    contact_subtitle: 'VỚI_TÔI',
    contact_emailLabel: 'ĐỊA_CHỈ_EMAIL',
    contact_phoneLabel: 'LIÊN_LẠC_BẢO_MẬT',
    contact_formName: 'ĐỊNH_DANH_NGƯỜI_DÙNG',
    contact_formEmail: 'ĐỊA_CHỈ_PHẢN_HỒI',
    contact_formMessage: 'DỮ_LIỆU_TRUYỀN_TẢI',
    contact_namePlaceholder: 'HỌ TÊN',
    contact_emailPlaceholder: 'EMAIL',
    contact_messagePlaceholder: 'NỘI DUNG TIN NHẮN',
    contact_submit: 'GỬI_GÓI_TIN',
    contact_sending: 'ĐANG_GỬI...',
    footer_copyright: '©2024_KINETIC_BRUTALISM_DEV.INIT()',
    footer_github: 'GITHUB',
    footer_linkedin: 'LINKEDIN',
    footer_source: 'MÃ_NGUỒN',
  },
  en: {
    navbar_home: 'HOME',
    navbar_about: 'ABOUT',
    navbar_experience: 'EXPERIENCE',
    navbar_skills: 'SKILLS',
    navbar_projects: 'PROJECTS',
    navbar_contact: 'CONNECT',
    hero_status: 'STATUS: ONLINE',
    hero_greeting: 'HELLO, I AM',
    hero_name: 'Bui Hoang Viet',
    hero_subtitle: 'Passionate Frontend Developer specializing in building modern web interfaces and seamless user experiences. Always learning new technologies to deliver quality products.',
    hero_btnProject: 'HIRE ME',
    hero_btnArsenal: 'DOWNLOAD CV',
    hero_expBadge: '8+',
    hero_expLabel: 'Years_Experience',
    hero_stat_years: 'Years_Experience',
    hero_stat_projects: 'Projects_Completed',
    hero_stat_tech: 'Technologies',
    hero_edu: 'UNETI — IT 2025',
    hero_student: 'Open to Work',
    narrative_title: 'Biography',
    about_title: 'Biography',
    about_fullname: 'Full_Name',
    about_fullname_val: 'Bui Hoang Viet',
    about_birth: 'Birthday',
    about_birth_val: '15/10/2003',
    about_university: 'University',
    about_univ_val: 'UNETI, Hanoi',
    about_gpa: 'GPA',
    about_gpa_val: '3.1 / 4.0',
    about_major: 'Major',
    about_major_val: 'Information Technology',
    about_email: 'Email',
    about_email_val: 'bhviet1510@gmail.com',
    about_phone: 'Phone',
    about_phone_val: '+84 912 687 955',
    about_location: 'Location',
    about_location_val: 'Hanoi, Vietnam',
    about_bio1: "I'm a passionate Frontend developer always seeking creative solutions for user interfaces. Proficient in Vue 3 and React to build modern, seamless web experiences.",
    about_bio2: "My goal is to continuously learn and develop professional skills to become a well-rounded Full-Stack Developer, contributing real value to the tech community.",
    about_edu_title: 'Education',
    about_school: 'University of Economics — Technology for Industries, Hanoi',
    about_major_school: 'Information Technology',
    about_goals_title: '3-Year_Goals',
    about_goal1: 'Become a professional Full-stack Developer',
    about_goal2: 'Master Cloud technologies (AWS / Azure)',
    about_goal3: 'Contribute to major Open Source projects',
    about_goal4: 'Build tech products that benefit the community',
    narrative_edu_label: 'SYSTEM_INITIALIZATION',
    narrative_edu_school: 'Hanoi University of Science and Technology',
    narrative_edu_period: '2014 — 2019',
    narrative_edu_degree: 'Bachelor of Computer Science',
    narrative_edu_gpa_label: 'GPA',
    narrative_edu_gpa: '3.8 / 4.0',
    narrative_career_section_title: 'Career_Summary',
    narrative_career_label: 'CAREER_TRAJECTORY',
    narrative_current_period: '2021 — PRESENT',
    narrative_current_title: 'Lead System Architect',
    narrative_current_summary: 'Designing fault-tolerant microservices architectures and leading core infrastructure scaling initiatives for Fintech platforms.',
    narrative_past_period: '2019 — 2021',
    narrative_past_title: 'Full-Stack Engineer',
    narrative_past_summary: 'Developing complex enterprise dashboards and high-performance APIs using the T3 stack and edge computing.',
    narrative_career_summary: '8 years building systems from microservices to monoliths. From intern at VNG to Lead System Architect at Monolith Systems JSC.',
    exp_title: 'Professional_Experience',
    exp_current: 'Present',
    exp_role1_company: 'SmartOSC',
    exp_role1_title: 'Frontend Developer Intern',
    exp_role1_period: '09/2025 — 11/2025',
    exp_role1_task1: 'Developed and maintained SPAs using Vue 3 and TypeScript, ensuring scalability and maintainability.',
    exp_role1_task2: 'Applied Composition API to modularize business logic into reusable composables.',
    exp_role1_task3: 'Managed global state using Pinia to optimize performance and ensure consistent data flow.',
    exp_role1_task4: 'Integrated RESTful APIs using Axios with proper async, loading, and error state handling.',
    exp_role1_task5: 'Built reusable UI components following best practices (props, emits, lifecycle hooks).',
    exp_role1_task6: 'Collaborated with team members using Git workflows (branching, pull requests, code reviews).',
    exp_role1_task7: 'Implemented responsive UI based on Figma designs, ensuring cross-device compatibility.',
    exp_role2_company: 'Mattech',
    exp_role2_title: 'Frontend Developer Intern',
    exp_role2_period: '11/2024 — 05/2025',
    exp_role2_task1: 'Developed and enhanced web interfaces using React and TypeScript with reusable component architecture.',
    exp_role2_task2: 'Implemented responsive and user-friendly UI using Tailwind CSS across multiple devices.',
    exp_role2_task3: 'Applied React Hooks (useState, useEffect, useMemo, useContext) for state management and performance optimization.',
    exp_role2_task4: 'Integrated RESTful APIs using Axios and ensured reliable data synchronization with backend systems.',
    exp_role2_task5: 'Collaborated with Laravel backend developers to align API structure and improve data handling efficiency.',
    exp_role2_task6: 'Managed source code with GitLab, participated in merge requests and code reviews.',
    exp_role2_task7: 'Actively contributed during key development phase (02/2025 — 04/2025), focusing on UI and API integration.',
    exp_role3_company: 'TD Clinic',
    exp_role3_title: 'Freelance Frontend Developer',
    exp_role3_period: '02/2025 — 04/2025',
    exp_role3_task1: 'Independently developed a full-featured medical clinic web platform with public website and multi-role dashboards (Admin, Doctor, Receptionist).',
    exp_role3_task2: 'Implemented role-based authentication and protected routing for secure access control.',
    exp_role3_task3: 'Built a complete appointment booking system with time slot selection, doctor assignment, and shift-based scheduling.',
    exp_role3_task4: 'Developed reusable and scalable UI components (DataTable, Modal, Pagination, FilterBar, StatsCard), reducing code duplication.',
    exp_role3_task5: 'Integrated RESTful APIs using Axios and managed global state with Redux Toolkit.',
    exp_role3_task6: 'Implemented data visualization dashboards (revenue, appointments, users) using charts for real-time monitoring.',
    exp_role3_task7: 'Applied i18next for Vietnamese and English language support.',
    exp_role3_task8: 'Optimized performance using lazy loading and code splitting; ensured responsive design and dark mode support.',
    exp_role3_task9: 'Deployed the application using Docker and Nginx in a production-like environment.',
    skill_title: 'Skills',
    skill_fe: '01. FRONTEND',
    skill_be: '02. BACKEND',
    skill_ui: '03. UI_LIBRARIES',
    skill_tools: '04. TOOLS',
    proj_title: 'Project_Archive',
    proj_deployed: 'DEPLOYED',
    proj_beta: 'BETA',
    proj_crypto_chart_name: 'Crypto Real-time Chart Dashboard',
    proj_crypto_chart_desc: 'Real-time cryptocurrency trading chart dashboard application, using WebSocket to stream OHLCV candlestick data directly from Binance with low latency. Supports multiple coin pairs and timeframes, displays candlestick + volume charts via lightweight-charts, integrates technical indicators (EMA, RSI), dark/light mode and continuously updates data without page reload.',
    proj_crypto_chart_tags: 'React 19 · TypeScript · Vite · Tailwind CSS · WebSocket · lightweight-charts · technicalindicators · Axios · Real-time Data · Financial Dashboard',
    proj_christmas_movie_name: 'Christmas Movie Marathon Landing Page',
    proj_christmas_movie_desc: 'Christmas movie event landing page built with React + TypeScript, allowing users to view schedules, select movies and register for tickets with quantity selection, seat availability check, and real-time pricing. Integrates Google Sheets as backend for registration data storage, combines festive UI with background music, multi-layer modals and responsive design.',
    proj_christmas_movie_tags: 'React 19 · TypeScript · Vite · Tailwind CSS · Google Sheets API · HTML5 Audio · Responsive Design · SPA · Event Landing Page',
    proj_clinic_td_name: 'T&D_Clinic_Management_System',
    proj_clinic_td_desc: 'Designed and developed a multi-role clinic management platform with fully isolated workflows for Admin, Receptionist, and Doctor dashboards. Engineered a reusable type-safe DataTable system with configurable columns, pagination, and CRUD modals to standardize data handling across the app. Built advanced medical record features including a dynamic prescription builder, treatment progress tracking, and before/after image management. Implemented role-based authentication with protected routing and centralized state using Redux Toolkit, alongside a complete i18n system (EN/VI) for localization.',
    proj_clinic_td_tags: 'React 19 · TypeScript · Redux Toolkit · React Router · Tailwind CSS · SCSS · Ant Design · Axios · i18next · Role-Based Architecture · Reusable Components · Vite',
    proj_sentinel_name: 'PROJECT_SENTINEL_V2',
    proj_sentinel_desc: 'Real-time performance monitoring system with Rust, WebAssembly and gRPC. Processing 1M+ events/second with sub-5ms latency.',
    proj_sentinel_tags: 'Rust · WebAssembly · gRPC',
    proj_aether_name: 'AETHER_NEXUS',
    proj_aether_desc: 'Centralized API gateway platform for microservices with intelligent load balancing and automatic rate limiting.',
    proj_aether_tags: 'Go · Redis · Kubernetes',
    proj_ecommerce_name: 'Sàn TMĐT',
    proj_ecommerce_desc: 'Website thương mại điện tử full chức năng, hỗ trợ giỏ hàng, thanh toán và quản lý sản phẩm.',
    proj_ecommerce_tags: 'Vue · Node.js · PostgreSQL',
    proj_fitapp_name: 'App Theo Dõi Tập Luyện',
    proj_fitapp_desc: 'Ứng dụng quản lý fitness, theo dõi lịch tập và dinh dưỡng hàng ngày trên thiết bị di động.',
    proj_fitapp_tags: 'React Native · Firebase',
    proj_corpweb_name: 'Website Doanh Nghiệp',
    proj_corpweb_desc: 'Landing page hiện đại cho doanh nghiệp, tối ưu SEO và responsive trên mọi thiết bị.',
    proj_corpweb_tags: 'React · Next.js · Tailwind',
    contact_title: 'Liên_Hệ',
    contact_subtitle: 'WITH_ME',
    contact_emailLabel: 'EMAIL_ADDRESS',
    contact_phoneLabel: 'SECURE_CONTACT',
    contact_formName: 'USER_IDENTIFIER',
    contact_formEmail: 'REPLY_ADDRESS',
    contact_formMessage: 'TRANSMISSION_DATA',
    contact_namePlaceholder: 'FULL NAME',
    contact_emailPlaceholder: 'EMAIL',
    contact_messagePlaceholder: 'YOUR MESSAGE',
    contact_submit: 'SEND_PACKET',
    contact_sending: 'SENDING...',
    footer_copyright: '©2024_KINETIC_BRUTALISM_DEV.INIT()',
    footer_github: 'GITHUB',
    footer_linkedin: 'LINKEDIN',
    footer_source: 'SOURCE',
  },
} as const;

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'vi';
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const t = (key: string): string => {
    return (translations[lang] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
